server:
  port: 10080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usercenter
    username: postgres
    password: postgres
    schema: classpath:import.sql
    # 创建数据库后可关闭，重启时不再创建
    initialize: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
          instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    health-check:
      enabled: true
account:
  api:
    application-name: User_Center_Service
